name: Android Build & Deploy

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Java environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Get latest version tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Determine version code and name
        id: determine_version
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            PR_NUMBER=$(jq -r '.number' $GITHUB_EVENT_PATH)
            PR_STATE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.state')
            if [[ $PR_STATE == 'closed' ]]; then
              echo "::set-output name=version_code::${{ steps.get_latest_tag.outputs.LATEST_TAG }}"
              echo "::set-output name=version_name::${{ steps.get_latest_tag.outputs.LATEST_TAG }}"
            else
              echo "::set-output name=version_code::${{ steps.get_latest_tag.outputs.LATEST_TAG + 1 }}"
              echo "::set-output name=version_name::${{ steps.get_latest_tag.outputs.LATEST_TAG + 1 }}"
            fi
          else
            echo "::set-output name=version_code::${{ steps.get_latest_tag.outputs.LATEST_TAG + 1 }}"
            echo "::set-output name=version_name::${{ steps.get_latest_tag.outputs.LATEST_TAG + 1 }}"
          fi

      - name: Rename APK with version
        run: |
          VERSION_CODE=${{ steps.determine_version.outputs.version_code }}
          VERSION_NAME=${{ steps.determine_version.outputs.version_name }}
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-$VERSION_NAME-$VERSION_CODE.apk

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/
